#未对程序进行封装，文件存取采用的是绝对地址
#数据预处理——统计历史信息
from IPython.core.interactiveshell import InteractiveShell
import pandas as pd
import time
import numpy as np
import sklearn.ensemble 
import lightgbm as lgb
from sklearn.metrics import log_loss
from lightgbm.sklearn import LGBMClassifier
from collections import Counter

InteractiveShell.ast_node_interactivity = 'all'
#数据读取部分
data = pd.read_csv('G:/Python/Alimama/Chusai/preprocessing_second_stage_data_v1.csv')
train_data = pd.read_csv('G:/Python/Alimama/Chusai/preprocessing_second_stage_train_data_v1.csv')
dev_data = pd.read_csv('G:/Python/Alimama/Chusai/preprocessing_second_stage_dev_data_v1.csv')
test_data = pd.read_csv('G:/Python/Alimama/Chusai/preprocessing_second_stage_test_data_v1.csv')
test1_data = pd.read_csv('G:/Python/Alimama/Chusai/preprocessing_second_stage_test1_data_v1.csv')
test2_data = pd.read_csv('G:/Python/Alimama/Chusai/preprocessing_second_stage_test2_data_v1.csv')

data.drop(['Unnamed: 0'],axis=1,inplace = True)
train_data.drop(['Unnamed: 0'],axis=1,inplace = True)
dev_data.drop(['Unnamed: 0'],axis=1,inplace = True)
test_data.drop(['Unnamed: 0'],axis=1,inplace = True)
test1_data.drop(['Unnamed: 0'],axis=1,inplace = True)
test2_data.drop(['Unnamed: 0'],axis=1,inplace = True)
all_data = pd.concat([data,test_data])

#统计展示时刻之前的历史点击次数
#-----------------------------------------训练集-------------------------------------------------
print('train_data start：')
train_data['user_id_lishi'] = train_data.apply(lambda x:len(train_data.loc[(train_data.user_id==x.user_id)
                                                &(train_data.context_timestamp_num<x.context_timestamp_num)]),axis=1)
print('1_finished')
train_data['item_id_lishi'] = train_data.apply(lambda x:len(train_data.loc[(train_data.item_id==x.item_id)
                                                &(train_data.context_timestamp_num<x.context_timestamp_num)]),axis=1)
print('2_finished')
train_data['shop_id_lishi'] = train_data.apply(lambda x:len(train_data.loc[(train_data.shop_id==x.shop_id)
                                                &(train_data.context_timestamp_num<x.context_timestamp_num)]),axis=1)
print('3_finished')
train_data['context_page_id_lishi'] = train_data.apply(lambda x:len(train_data.loc[(train_data.context_page_id==x.context_page_id)
                                                &(train_data.context_timestamp_num<x.context_timestamp_num)]),axis=1)
print('4_finished')
train_data['category_second_lishi'] = train_data.apply(lambda x:len(train_data.loc[(train_data.item_category_list_second==x.item_category_list_second)
                                                &(train_data.context_timestamp_num<x.context_timestamp_num)]),axis=1)
print('5_finished')
train_data['item_id_user_id_lishi'] = train_data.apply(lambda x:len(train_data.loc[(train_data.item_id==x.item_id)
                                                &(train_data.user_id==x.user_id)
                                                &(train_data.context_timestamp_num<x.context_timestamp_num)]),axis=1)
print('6_finished')
train_data['item_id_user_age_lishi'] = train_data.apply(lambda x:len(train_data.loc[(train_data.item_id==x.item_id)
                                                &(train_data.user_age_level==x.user_age_level)
                                                &(train_data.context_timestamp_num<x.context_timestamp_num)]),axis=1)
print('7_finished')
train_data['shop_id_user_id_lishi'] = train_data.apply(lambda x:len(train_data.loc[(train_data.shop_id==x.shop_id)
                                                &(train_data.user_id==x.user_id)
                                                &(train_data.context_timestamp_num<x.context_timestamp_num)]),axis=1)
print('8_finished')
train_data['category_second_user_id_lishi'] = train_data.apply(lambda x:len(train_data.loc[(train_data.user_id==x.user_id)
                                                &(train_data.item_category_list_second==x.item_category_list_second)
                                                &(train_data.context_timestamp_num<x.context_timestamp_num)]),axis=1)
print('9_finished')
train_data['context_page_id_brand_id_lishi'] = train_data.apply(lambda x:len(train_data.loc[(train_data.item_brand_id==x.item_brand_id)
                                                &(train_data.context_page_id==x.context_page_id)
                                                &(train_data.context_timestamp_num<x.context_timestamp_num)]),axis=1)
print('10_finished')
train_data['category_second_brand_id_lishi'] = train_data.apply(lambda x:len(train_data.loc[(train_data.item_brand_id==x.item_brand_id)
                                                &(train_data.item_category_list_second==x.item_category_list_second)
                                                &(train_data.context_timestamp_num<x.context_timestamp_num)]),axis=1)
print('11_finished')
print('train_data_finished!')
#-----------------------------------------开发集-------------------------------------------------
print('dev_data start：')
dev_data['user_id_lishi'] = dev_data.apply(lambda x:len(data.loc[(data.user_id==x.user_id)
                                                &(data.context_timestamp_num<x.context_timestamp_num)]),axis=1)
dev_data['item_id_lishi'] = dev_data.apply(lambda x:len(data.loc[(data.item_id==x.item_id)
                                                &(data.context_timestamp_num<x.context_timestamp_num)]),axis=1)
dev_data['shop_id_lishi'] = dev_data.apply(lambda x:len(data.loc[(data.shop_id==x.shop_id)
                                                &(data.context_timestamp_num<x.context_timestamp_num)]),axis=1)
dev_data['context_page_id_lishi'] = dev_data.apply(lambda x:len(data.loc[(data.context_page_id==x.context_page_id)
                                                &(data.context_timestamp_num<x.context_timestamp_num)]),axis=1)
dev_data['category_second_lishi'] = dev_data.apply(lambda x:len(data.loc[(data.item_category_list_second==x.item_category_list_second)
                                                &(data.context_timestamp_num<x.context_timestamp_num)]),axis=1)
dev_data['item_id_user_id_lishi'] = dev_data.apply(lambda x:len(data.loc[(data.item_id==x.item_id)
                                                &(data.user_id==x.user_id)
                                                &(data.context_timestamp_num<x.context_timestamp_num)]),axis=1)
dev_data['item_id_user_age_lishi'] = dev_data.apply(lambda x:len(data.loc[(data.item_id==x.item_id)
                                                &(data.user_age_level==x.user_age_level)
                                                &(data.context_timestamp_num<x.context_timestamp_num)]),axis=1)
dev_data['shop_id_user_id_lishi'] = dev_data.apply(lambda x:len(data.loc[(data.shop_id==x.shop_id)
                                                &(data.user_id==x.user_id)
                                                &(data.context_timestamp_num<x.context_timestamp_num)]),axis=1)
dev_data['category_second_user_id_lishi'] = dev_data.apply(lambda x:len(data.loc[(data.user_id==x.user_id)
                                                &(data.item_category_list_second==x.item_category_list_second)
                                                &(data.context_timestamp_num<x.context_timestamp_num)]),axis=1)
dev_data['context_page_id_brand_id_lishi'] = dev_data.apply(lambda x:len(data.loc[(data.item_brand_id==x.item_brand_id)
                                                &(data.context_page_id==x.context_page_id)
                                                &(data.context_timestamp_num<x.context_timestamp_num)]),axis=1)
dev_data['category_second_brand_id_lishi'] = dev_data.apply(lambda x:len(data.loc[(data.item_brand_id==x.item_brand_id)
                                                &(data.item_category_list_second==x.item_category_list_second)
                                                &(data.context_timestamp_num<x.context_timestamp_num)]),axis=1)
print('dev_data_finished!')
#-----------------------------------------验证集-------------------------------------------------
print('test_data start：')
test_data['user_id_lishi'] = test_data.apply(lambda x:len(all_data.loc[(all_data.user_id==x.user_id)
                                                &(all_data.context_timestamp_num<x.context_timestamp_num)]),axis=1)
test_data['item_id_lishi'] = test_data.apply(lambda x:len(all_data.loc[(all_data.item_id==x.item_id)
                                                &(all_data.context_timestamp_num<x.context_timestamp_num)]),axis=1)
test_data['shop_id_lishi'] = test_data.apply(lambda x:len(all_data.loc[(all_data.shop_id==x.shop_id)
                                                &(all_data.context_timestamp_num<x.context_timestamp_num)]),axis=1)
test_data['context_page_id_lishi'] = test_data.apply(lambda x:len(all_data.loc[(all_data.context_page_id==x.context_page_id)
                                                &(all_data.context_timestamp_num<x.context_timestamp_num)]),axis=1)
test_data['category_second_lishi'] = test_data.apply(lambda x:len(all_data.loc[(all_data.item_category_list_second==x.item_category_list_second)
                                                &(all_data.context_timestamp_num<x.context_timestamp_num)]),axis=1)
test_data['item_id_user_id_lishi'] = test_data.apply(lambda x:len(all_data.loc[(all_data.item_id==x.item_id)
                                                &(all_data.user_id==x.user_id)
                                                &(all_data.context_timestamp_num<x.context_timestamp_num)]),axis=1)
test_data['item_id_user_age_lishi'] = test_data.apply(lambda x:len(all_data.loc[(all_data.item_id==x.item_id)
                                                &(all_data.user_age_level==x.user_age_level)
                                                &(all_data.context_timestamp_num<x.context_timestamp_num)]),axis=1)
test_data['shop_id_user_id_lishi'] = test_data.apply(lambda x:len(all_data.loc[(all_data.shop_id==x.shop_id)
                                                &(all_data.user_id==x.user_id)
                                                &(all_data.context_timestamp_num<x.context_timestamp_num)]),axis=1)
test_data['category_second_user_id_lishi'] = test_data.apply(lambda x:len(all_data.loc[(all_data.user_id==x.user_id)
                                                &(all_data.item_category_list_second==x.item_category_list_second)
                                                &(all_data.context_timestamp_num<x.context_timestamp_num)]),axis=1)
test_data['context_page_id_brand_id_lishi'] = test_data.apply(lambda x:len(all_data.loc[(all_data.item_brand_id==x.item_brand_id)
                                                &(all_data.context_page_id==x.context_page_id)
                                                &(all_data.context_timestamp_num<x.context_timestamp_num)]),axis=1)
test_data['category_second_brand_id_lishi'] = test_data.apply(lambda x:len(all_data.loc[(all_data.item_brand_id==x.item_brand_id)
                                                &(all_data.item_category_list_second==x.item_category_list_second)
                                                &(all_data.context_timestamp_num<x.context_timestamp_num)]),axis=1)
print('test_data_finished!')

test1_data_pre,test2_data_pre = test_data[:test1_data.shape[0]],test_data[test1_data.shape[0]:]
data_all = pd.concat([train_data,dev_data])
#
data_all.to_csv('G:/Python/Alimama/Chusai/preprocessing_second_stage_data_v2.csv')
train_data.to_csv('G:/Python/Alimama/Chusai/preprocessing_second_stage_train_data_v2.csv')
dev_data.to_csv('G:/Python/Alimama/Chusai/preprocessing_second_stage_dev_data_v2.csv')
test_data.to_csv('G:/Python/Alimama/Chusai/preprocessing_second_stage_test_data_v2.csv')
test1_data_pre.to_csv('G:/Python/Alimama/Chusai/preprocessing_second_stage_test1_data_v2.csv')
#test2_data为初赛二阶段提交的data
test2_data_pre.to_csv('G:/Python/Alimama/Chusai/preprocessing_second_stage_test2_data_v2.csv')
