#未对程序进行封装，文件读取采用的是绝对路径
from IPython.core.interactiveshell import InteractiveShell
import pandas as pd
import time
import numpy as np
import sklearn.ensemble 
import lightgbm as lgb
from sklearn.metrics import log_loss
from lightgbm.sklearn import LGBMClassifier
from collections import Counter

InteractiveShell.ast_node_interactivity = 'all'

data = pd.read_csv('G:/Python/Alimama/Chusai/preprocessing_second_stage_data_v3.csv')
train_data = pd.read_csv('G:/Python/Alimama/Chusai/preprocessing_second_stage_train_data_v3.csv')
dev_data = pd.read_csv('G:/Python/Alimama/Chusai/preprocessing_second_stage_dev_data_v3.csv')
test_data = pd.read_csv('G:/Python/Alimama/Chusai/preprocessing_second_stage_test_data_v3.csv')
test1_data = pd.read_csv('G:/Python/Alimama/Chusai/preprocessing_second_stage_test1_data_v3.csv')
test2_data = pd.read_csv('G:/Python/Alimama/Chusai/preprocessing_second_stage_test2_data_v3.csv')

data.drop(['Unnamed: 0'],axis=1,inplace = True)
train_data.drop(['Unnamed: 0'],axis=1,inplace = True)
dev_data.drop(['Unnamed: 0'],axis=1,inplace = True)
test_data.drop(['Unnamed: 0'],axis=1,inplace = True)
test1_data.drop(['Unnamed: 0'],axis=1,inplace = True)
test2_data.drop(['Unnamed: 0'],axis=1,inplace = True)
all_data = pd.concat([data,test_data])
#**************************************************************************************************
#----------------------------------------------数据预处理——全局统计量--------------------------------------
user_id_all = all_data.groupby(['user_id']).size().reset_index().rename(columns={0:'user_id_all'})
item_id_all = all_data.groupby(['item_id']).size().reset_index().rename(columns={0:'item_id_all'})
category_second_all = all_data.groupby(['item_category_list_second']).size().reset_index().rename(columns={0:'category_second_all'})
context_page_id_all = all_data.groupby(['context_page_id']).size().reset_index().rename(columns={0:'context_page_id_all'})
user_id_item_id_all = all_data.groupby(['user_id','item_id']).size().reset_index().rename(columns={0:'user_id_item_id_all'})
user_id_category_second_all = all_data.groupby(['user_id','item_category_list_second']).size().reset_index().rename(columns={0:'user_id_category_second_all'})
user_id_context_page_all = all_data.groupby(['user_id','context_page_id']).size().reset_index().rename(columns={0:'user_id_context_page_all'})
user_id_item_price_all = all_data.groupby(['user_id','item_price_level']).size().reset_index().rename(columns={0:'user_id_item_price_all'})
user_id_shop_id_all = all_data.groupby(['user_id','shop_id']).size().reset_index().rename(columns={0:'user_id_shop_id_all'})
context_page_id_brand_id_all = all_data.groupby(['context_page_id','item_brand_id']).size().reset_index().rename(columns={0:'context_page_id_brand_id_all'})
category_second_brand_id_all = all_data.groupby(['item_category_list_second','item_brand_id']).size().reset_index().rename(columns={0:'category_second_brand_id_all'})
#---------------------------------------------------训练集------------------------------------------------
train_data = pd.merge(train_data,user_id_all,'left',on=['user_id'])
train_data = pd.merge(train_data,item_id_all,'left',on=['item_id'])
train_data = pd.merge(train_data,category_second_all,'left',on=['item_category_list_second'])
train_data = pd.merge(train_data,context_page_id_all,'left',on=['context_page_id'])
train_data = pd.merge(train_data,user_id_item_id_all,'left',on=['user_id','item_id'])
train_data = pd.merge(train_data,user_id_category_second_all,'left',on=['user_id','item_category_list_second'])
train_data = pd.merge(train_data,user_id_context_page_all,'left',on=['user_id','context_page_id'])
train_data = pd.merge(train_data,user_id_item_price_all,'left',on=['user_id','item_price_level'])
train_data = pd.merge(train_data,user_id_shop_id_all,'left',on=['user_id','shop_id'])
train_data = pd.merge(train_data,context_page_id_brand_id_all,'left',on=['context_page_id','item_brand_id'])
train_data = pd.merge(train_data,category_second_brand_id_all,'left',on=['item_category_list_second','item_brand_id'])
#---------------------------------------------------开发集------------------------------------------------
dev_data = pd.merge(dev_data,user_id_all,'left',on=['user_id'])
dev_data = pd.merge(dev_data,item_id_all,'left',on=['item_id'])
dev_data = pd.merge(dev_data,category_second_all,'left',on=['item_category_list_second'])
dev_data = pd.merge(dev_data,context_page_id_all,'left',on=['context_page_id'])
dev_data = pd.merge(dev_data,user_id_item_id_all,'left',on=['user_id','item_id'])
dev_data = pd.merge(dev_data,user_id_category_second_all,'left',on=['user_id','item_category_list_second'])
dev_data = pd.merge(dev_data,user_id_context_page_all,'left',on=['user_id','context_page_id'])
dev_data = pd.merge(dev_data,user_id_item_price_all,'left',on=['user_id','item_price_level'])
dev_data = pd.merge(dev_data,user_id_shop_id_all,'left',on=['user_id','shop_id'])
dev_data = pd.merge(dev_data,context_page_id_brand_id_all,'left',on=['context_page_id','item_brand_id'])
dev_data = pd.merge(dev_data,category_second_brand_id_all,'left',on=['item_category_list_second','item_brand_id'])
#---------------------------------------------------测试集------------------------------------------------
test_data = pd.merge(test_data,user_id_all,'left',on=['user_id'])
test_data = pd.merge(test_data,item_id_all,'left',on=['item_id'])
test_data = pd.merge(test_data,category_second_all,'left',on=['item_category_list_second'])
test_data = pd.merge(test_data,context_page_id_all,'left',on=['context_page_id'])
test_data = pd.merge(test_data,user_id_item_id_all,'left',on=['user_id','item_id'])
test_data = pd.merge(test_data,user_id_category_second_all,'left',on=['user_id','item_category_list_second'])
test_data = pd.merge(test_data,user_id_context_page_all,'left',on=['user_id','context_page_id'])
test_data = pd.merge(test_data,user_id_item_price_all,'left',on=['user_id','item_price_level'])
test_data = pd.merge(test_data,user_id_shop_id_all,'left',on=['user_id','shop_id'])
test_data = pd.merge(test_data,context_page_id_brand_id_all,'left',on=['context_page_id','item_brand_id'])
test_data = pd.merge(test_data,category_second_brand_id_all,'left',on=['item_category_list_second','item_brand_id'])
#**************************************************************************************************************************
#-------------------------------------------数据预处理——每天统计量-------------------------------------------------------
#---------------------------------------------------训练集------------------------------------------------
train_user_id_day = train_data.groupby(['user_id','Day']).size().reset_index().rename(columns={0:'user_id_day'})
train_item_id_day = train_data.groupby(['item_id','Day']).size().reset_index().rename(columns={0:'item_id_day'})
train_category_second_day = train_data.groupby(['item_category_list_second','Day']).size().reset_index().rename(columns={0:'category_second_day'})
train_context_page_id_day = train_data.groupby(['context_page_id','Day']).size().reset_index().rename(columns={0:'context_page_id_day'})
train_user_id_item_id_day = train_data.groupby(['user_id','item_id','Day']).size().reset_index().rename(columns={0:'user_id_item_id_day'})
train_user_id_category_second_day = train_data.groupby(['user_id','item_category_list_second','Day']).size().reset_index().rename(columns={0:'user_id_category_second_day'})
train_user_id_context_page_day = train_data.groupby(['user_id','context_page_id','Day']).size().reset_index().rename(columns={0:'user_id_context_page_day'})
train_user_id_item_price_day = train_data.groupby(['user_id','item_price_level','Day']).size().reset_index().rename(columns={0:'user_id_item_price_day'})
train_user_id_shop_id_day = train_data.groupby(['user_id','shop_id','Day']).size().reset_index().rename(columns={0:'user_id_shop_id_day'})
train_user_id_brand_id_day = train_data.groupby(['user_id','item_brand_id','Day']).size().reset_index().rename(columns={0:'user_id_brand_id_day'})
train_context_page_id_brand_id_day = train_data.groupby(['context_page_id','item_brand_id','Day']).size().reset_index().rename(columns={0:'context_page_id_brand_id_day'})
train_category_second_brand_id_day = train_data.groupby(['item_category_list_second','item_brand_id','Day']).size().reset_index().rename(columns={0:'category_second_brand_id_day'})
train_user_age_item_price_day = train_data.groupby(['user_age_level','item_price_level','Day']).size().reset_index().rename(columns={0:'user_age_price_level_day'})
train_user_age_item_sales_day = train_data.groupby(['user_age_level','item_sales_level','Day']).size().reset_index().rename(columns={0:'user_age_sales_level_day'})
train_user_gender_item_price_day = train_data.groupby(['user_gender_id','item_price_level','Day']).size().reset_index().rename(columns={0:'user_gender_price_level_day'})
train_user_gender_item_sales_day = train_data.groupby(['user_gender_id','item_sales_level','Day']).size().reset_index().rename(columns={0:'user_gender_sales_level_day'})

train_data = pd.merge(train_data,train_user_id_day,'left',on=['user_id','Day'])
train_data = pd.merge(train_data,train_item_id_day,'left',on=['item_id','Day'])
train_data = pd.merge(train_data,train_category_second_day,'left',on=['item_category_list_second','Day'])
train_data = pd.merge(train_data,train_context_page_id_day,'left',on=['context_page_id','Day'])
train_data = pd.merge(train_data,train_user_id_item_id_day,'left',on=['user_id','item_id','Day'])
train_data = pd.merge(train_data,train_user_id_category_second_day,'left',on=['user_id','item_category_list_second','Day'])
train_data = pd.merge(train_data,train_user_id_context_page_day,'left',on=['user_id','context_page_id','Day'])
train_data = pd.merge(train_data,train_user_id_item_price_day,'left',on=['user_id','item_price_level','Day'])
train_data = pd.merge(train_data,train_user_id_shop_id_day,'left',on=['user_id','shop_id','Day'])
train_data = pd.merge(train_data,train_user_id_brand_id_day,'left',on=['user_id','item_brand_id','Day'])
train_data = pd.merge(train_data,train_context_page_id_brand_id_day,'left',on=['context_page_id','item_brand_id','Day'])
train_data = pd.merge(train_data,train_category_second_brand_id_day,'left',on=['item_category_list_second','item_brand_id','Day'])
train_data = pd.merge(train_data,train_user_age_item_price_day,'left',on=['user_age_level','item_price_level','Day'])
train_data = pd.merge(train_data,train_user_age_item_sales_day,'left',on=['user_age_level','item_sales_level','Day'])
train_data = pd.merge(train_data,train_user_gender_item_price_day,'left',on=['user_gender_id','item_price_level','Day'])
train_data = pd.merge(train_data,train_user_gender_item_sales_day,'left',on=['user_gender_id','item_sales_level','Day'])
#---------------------------------------------------开发集------------------------------------------------
dev_user_id_day = dev_data.groupby(['user_id','Day']).size().reset_index().rename(columns={0:'user_id_day'})
dev_item_id_day = dev_data.groupby(['item_id','Day']).size().reset_index().rename(columns={0:'item_id_day'})
dev_category_second_day = dev_data.groupby(['item_category_list_second','Day']).size().reset_index().rename(columns={0:'category_second_day'})
dev_context_page_id_day = dev_data.groupby(['context_page_id','Day']).size().reset_index().rename(columns={0:'context_page_id_day'})
dev_user_id_item_id_day = dev_data.groupby(['user_id','item_id','Day']).size().reset_index().rename(columns={0:'user_id_item_id_day'})
dev_user_id_category_second_day = dev_data.groupby(['user_id','item_category_list_second','Day']).size().reset_index().rename(columns={0:'user_id_category_second_day'})
dev_user_id_context_page_day = dev_data.groupby(['user_id','context_page_id','Day']).size().reset_index().rename(columns={0:'user_id_context_page_day'})
dev_user_id_item_price_day = dev_data.groupby(['user_id','item_price_level','Day']).size().reset_index().rename(columns={0:'user_id_item_price_day'})
dev_user_id_shop_id_day = dev_data.groupby(['user_id','shop_id','Day']).size().reset_index().rename(columns={0:'user_id_shop_id_day'})
dev_user_id_brand_id_day = dev_data.groupby(['user_id','item_brand_id','Day']).size().reset_index().rename(columns={0:'user_id_brand_id_day'})
dev_context_page_id_brand_id_day = dev_data.groupby(['context_page_id','item_brand_id','Day']).size().reset_index().rename(columns={0:'context_page_id_brand_id_day'})
dev_category_second_brand_id_day = dev_data.groupby(['item_category_list_second','item_brand_id','Day']).size().reset_index().rename(columns={0:'category_second_brand_id_day'})
dev_user_age_item_price_day = dev_data.groupby(['user_age_level','item_price_level','Day']).size().reset_index().rename(columns={0:'user_age_price_level_day'})
dev_user_age_item_sales_day = dev_data.groupby(['user_age_level','item_sales_level','Day']).size().reset_index().rename(columns={0:'user_age_sales_level_day'})
dev_user_gender_item_price_day = dev_data.groupby(['user_gender_id','item_price_level','Day']).size().reset_index().rename(columns={0:'user_gender_price_level_day'})
dev_user_gender_item_sales_day = dev_data.groupby(['user_gender_id','item_sales_level','Day']).size().reset_index().rename(columns={0:'user_gender_sales_level_day'})

dev_data = pd.merge(dev_data,dev_user_id_day,'left',on=['user_id','Day'])
dev_data = pd.merge(dev_data,dev_item_id_day,'left',on=['item_id','Day'])
dev_data = pd.merge(dev_data,dev_category_second_day,'left',on=['item_category_list_second','Day'])
dev_data = pd.merge(dev_data,dev_context_page_id_day,'left',on=['context_page_id','Day'])
dev_data = pd.merge(dev_data,dev_user_id_item_id_day,'left',on=['user_id','item_id','Day'])
dev_data = pd.merge(dev_data,dev_user_id_category_second_day,'left',on=['user_id','item_category_list_second','Day'])
dev_data = pd.merge(dev_data,dev_user_id_context_page_day,'left',on=['user_id','context_page_id','Day'])
dev_data = pd.merge(dev_data,dev_user_id_item_price_day,'left',on=['user_id','item_price_level','Day'])
dev_data = pd.merge(dev_data,dev_user_id_shop_id_day,'left',on=['user_id','shop_id','Day'])
dev_data = pd.merge(dev_data,dev_user_id_brand_id_day,'left',on=['user_id','item_brand_id','Day'])
dev_data = pd.merge(dev_data,dev_context_page_id_brand_id_day,'left',on=['context_page_id','item_brand_id','Day'])
dev_data = pd.merge(dev_data,dev_category_second_brand_id_day,'left',on=['item_category_list_second','item_brand_id','Day'])
dev_data = pd.merge(dev_data,dev_user_age_item_price_day,'left',on=['user_age_level','item_price_level','Day'])
dev_data = pd.merge(dev_data,dev_user_age_item_sales_day,'left',on=['user_age_level','item_sales_level','Day'])
dev_data = pd.merge(dev_data,dev_user_gender_item_price_day,'left',on=['user_gender_id','item_price_level','Day'])
dev_data = pd.merge(dev_data,dev_user_gender_item_sales_day,'left',on=['user_gender_id','item_sales_level','Day'])
#---------------------------------------------------测试集------------------------------------------------
test_user_id_day = test_data.groupby(['user_id','Day']).size().reset_index().rename(columns={0:'user_id_day'})
test_item_id_day = test_data.groupby(['item_id','Day']).size().reset_index().rename(columns={0:'item_id_day'})
test_category_second_day = test_data.groupby(['item_category_list_second','Day']).size().reset_index().rename(columns={0:'category_second_day'})
test_context_page_id_day = test_data.groupby(['context_page_id','Day']).size().reset_index().rename(columns={0:'context_page_id_day'})
test_user_id_item_id_day = test_data.groupby(['user_id','item_id','Day']).size().reset_index().rename(columns={0:'user_id_item_id_day'})
test_user_id_category_second_day = test_data.groupby(['user_id','item_category_list_second','Day']).size().reset_index().rename(columns={0:'user_id_category_second_day'})
test_user_id_context_page_day = test_data.groupby(['user_id','context_page_id','Day']).size().reset_index().rename(columns={0:'user_id_context_page_day'})
test_user_id_item_price_day = test_data.groupby(['user_id','item_price_level','Day']).size().reset_index().rename(columns={0:'user_id_item_price_day'})
test_user_id_shop_id_day = test_data.groupby(['user_id','shop_id','Day']).size().reset_index().rename(columns={0:'user_id_shop_id_day'})
test_user_id_brand_id_day = test_data.groupby(['user_id','item_brand_id','Day']).size().reset_index().rename(columns={0:'user_id_brand_id_day'})
test_context_page_id_brand_id_day = test_data.groupby(['context_page_id','item_brand_id','Day']).size().reset_index().rename(columns={0:'context_page_id_brand_id_day'})
test_category_second_brand_id_day = test_data.groupby(['item_category_list_second','item_brand_id','Day']).size().reset_index().rename(columns={0:'category_second_brand_id_day'})
test_user_age_item_price_day = test_data.groupby(['user_age_level','item_price_level','Day']).size().reset_index().rename(columns={0:'user_age_price_level_day'})
test_user_age_item_sales_day = test_data.groupby(['user_age_level','item_sales_level','Day']).size().reset_index().rename(columns={0:'user_age_sales_level_day'})
test_user_gender_item_price_day = test_data.groupby(['user_gender_id','item_price_level','Day']).size().reset_index().rename(columns={0:'user_gender_price_level_day'})
test_user_gender_item_sales_day = test_data.groupby(['user_gender_id','item_sales_level','Day']).size().reset_index().rename(columns={0:'user_gender_sales_level_day'})

test_data = pd.merge(test_data,test_user_id_day,'left',on=['user_id','Day'])
test_data = pd.merge(test_data,test_item_id_day,'left',on=['item_id','Day'])
test_data = pd.merge(test_data,test_category_second_day,'left',on=['item_category_list_second','Day'])
test_data = pd.merge(test_data,test_context_page_id_day,'left',on=['context_page_id','Day'])
test_data = pd.merge(test_data,test_user_id_item_id_day,'left',on=['user_id','item_id','Day'])
test_data = pd.merge(test_data,test_user_id_category_second_day,'left',on=['user_id','item_category_list_second','Day'])
test_data = pd.merge(test_data,test_user_id_context_page_day,'left',on=['user_id','context_page_id','Day'])
test_data = pd.merge(test_data,test_user_id_item_price_day,'left',on=['user_id','item_price_level','Day'])
test_data = pd.merge(test_data,test_user_id_shop_id_day,'left',on=['user_id','shop_id','Day'])
test_data = pd.merge(test_data,test_user_id_brand_id_day,'left',on=['user_id','item_brand_id','Day'])
test_data = pd.merge(test_data,test_context_page_id_brand_id_day,'left',on=['context_page_id','item_brand_id','Day'])
test_data = pd.merge(test_data,test_category_second_brand_id_day,'left',on=['item_category_list_second','item_brand_id','Day'])
test_data = pd.merge(test_data,test_user_age_item_price_day,'left',on=['user_age_level','item_price_level','Day'])
test_data = pd.merge(test_data,test_user_age_item_sales_day,'left',on=['user_age_level','item_sales_level','Day'])
test_data = pd.merge(test_data,test_user_gender_item_price_day,'left',on=['user_gender_id','item_price_level','Day'])
test_data = pd.merge(test_data,test_user_gender_item_sales_day,'left',on=['user_gender_id','item_sales_level','Day'])

test1_data_pre,test2_data_pre = test_data[:test1_data.shape[0]],test_data[test1_data.shape[0]:]
data_all = pd.concat([train_data,dev_data])
data_all.to_csv('G:/Python/Alimama/Chusai/preprocessing_second_stage_data_v4.csv')
train_data.to_csv('G:/Python/Alimama/Chusai/preprocessing_second_stage_train_data_v4.csv')
dev_data.to_csv('G:/Python/Alimama/Chusai/preprocessing_second_stage_dev_data_v4.csv')
test_data.to_csv('G:/Python/Alimama/Chusai/preprocessing_second_stage_test_data_v4.csv')
test1_data_pre.to_csv('G:/Python/Alimama/Chusai/preprocessing_second_stage_test1_data_v4.csv')
#test2_data为初赛二阶段提交的data
test2_data_pre.to_csv('G:/Python/Alimama/Chusai/preprocessing_second_stage_test2_data_v4.csv')

